### ISSUE TITLE
全くスクロールしていない時に「上に戻る」ボタンを押すとスクロールできなくなる場合がある

### ISSUE THREAD

**Issue by oka4shi** [Hayao0819/hayao-old-website#2]
### 現象
全くスクロールしていない時に「上に戻る」ボタンを押すと、スクロールしようとしてもすぐ一番上に戻ってしまいスクロールできなくなる場合があります。

- 300ms固定されてその後動くようになるパターン(毎回発生)
- 5秒近く動かなくなるパターン(ブラウザの幅を変えた時に発生)

の2つを確認しています

### 環境
- Firefox 86.0b9
- Google Chrome 88.0.4324.182
- Microsoft Edge 88.0.705.74
の全てで発生しました。

### 考えられる修正方法

これを修正するには、
- スクロールされてないときにはボタンを押しても何もしない
- スクロールするまで「上に戻る」ボタンを非表示にする

という対策が考えられますが、どっちがいいでしょうか？

ハヤオさんの意見を聞いた上で修正のプルリクを出そうと思っています。

**Comment by Hayao0819** [comment]
スクロールされたときのみボタンを表示するようにしました
