### ISSUE TITLE
誤字 https://hayao.fascode.net/buildmydist-2/pages/release/

### ISSUE THREAD

**Issue by awayume** [Hayao0819/hayao-old-website#8]
「青果物をアップロードする」は、「成果物をアップロードする」だと思います。

**Comment by nuko6925** [comment]
https://hayao.fascode.net/buildmydist-2/pages/common/
保存っしておくと合っというま
保存しておくとあっという間

**Comment by Hayao0819** [comment]
ありがとうございます。修正しました。
