### ISSUE TITLE
aタグのURL先がlocalhost

### ISSUE THREAD

**Issue by 2315195882** [Hayao0819/hayao-old-website#9]
http://hayao.fascode.net/buildmydist-2/pages/ubuntu1804/preparation/

の「それ以外に必要な物はすべて"[はじめに](http://localhost/buildmydist-2/pages/common)"で紹介しているのでそちらを参照してください。」この部分「はじめに](http://localhost/buildmydist-2/pages/common)」がlocalhostにされている。

修正案は「https://hayao.fascode.net/buildmydist-2/pages/common/」こうする

**Comment by Hayao0819** [comment]
ほんとだ...ありがとうございます
今体調が悪いので治り次第修正します

**Comment by naoko1010hh** [comment]
時間があったので修正してみました。
https://hayao.fascode.net/buildmydist-2/pages/common/
という提案でしたが
/buildmydist-2/pages/common/
だけにしました理由としましてはphpを使用されてるWEBサーバー上で動かす前提になっているため/開始でもないとおもいます。
問題なければpull承認よろしくお願いします。
